### ISSUE TITLE
Can we move away from using tilesets for terrain?

### ISSUE THREAD

**Issue by resindrake** [HazDroneCorp/frontiersmen#41]
Is there another, more efficient (resource-wise) method we could use that completely forgoes tilesets for making the terrain? I feel like tilesets don't fit our needs.

Perhaps we could store the world as geometric data and then essentially 'nearest-neighbor' assign ground textures?
Also, for artificial structures, we could use a 9rect-like object to make rooms of any shape or size, perhaps?

Let me know what possible alternatives might work!

**Comment by Krutonium** [comment]
The problem, as I see it, boils down to the fact that tilesets are the best thing for the job. They provide collision, can occlude light, you can change them easily, etc. Nothing else has that particular set of properties.
